# Catalog that supports Octybot
#WARNING: The name that your are going to assign, needs to be the same as the file that you want to call.
# The download file is in utils folder as download_models.sh and the ensure_model or validation is in utils.py

stt:
#Whisper models
  - name: base.pt
    url: "https://openaipublic.azureedge.net/main/whisper/models/ed3a0b6b1c0edf879ad9b11b1af5a0e6ab5db9205f891f668f8b0e6c6326e34e/base.pt"

  - name: small.pt
    url: "https://openaipublic.azureedge.net/main/whisper/models/9ecf779972d90ba49c06d968637d720dd632c55bbf19d441fb42bf17a411e794/small.pt"

tts:
#Piper Models
# WARNING: The order of the models is important, first the voice model and then the decoder model.
# Unless the function voice_pair to select the voice is going to be useless

  - name: es_419-Octybot-medium.onnx
    url: "https://drive.google.com/uc?export=download&id=1XwlJHb9tIEBkZP21uj-HKznvuJ-NSRJS"
    
  - name: es_419-Octybot-medium.onnx.json
    url: "https://drive.google.com/uc?export=download&id=1OdOvI7z5GBilV-jRNjmCR8F3G15q2Bx4"

  - name: es_MX-claude-high.onnx
    url: https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/claude/high/es_MX-claude-high.onnx?download=true

  - name: es_MX-claude-high.onnx.json
    url: https://huggingface.co/rhasspy/piper-voices/resolve/main/es/es_MX/claude/high/es_MX-claude-high.onnx.json?download=true

wake_word:
#Vosk Models
  - name: vosk-model-small-es-0.42
    url: https://alphacephei.com/vosk/models/vosk-model-small-es-0.42.zip
